/**
 * ═══════════════════════════════════════════════════════════
 *  MALADIES INFECTIEUSES — Constantes & Examens spécifiques
 *  ═══════════════════════════════════════════════════════════
 */

export const EXAMENS_MALINF = {
  "VIH/SIDA": [
    "Test de dépistage VIH",
    "Test rapide VIH",
    "Western Blot VIH",
    "Charge virale VIH",
    "CD4/CD8",
    "Lymphocytes T4",
    "Test de résistance",
    "Génotypage",
  ],
  "Hépatites virales": [
    "Sérologie Hépatite A",
    "Sérologie Hépatite B",
    "Sérologie Hépatite C",
    "Sérologie Hépatite D",
    "Sérologie Hépatite E",
    "Charge virale VHB",
    "Charge virale VHC",
    "Génotypage VHC",
    "Antigène HBs",
    "Anticorps anti-HBs",
    "Anticorps anti-HBc",
  ],
  "Tuberculose": [
    "IDR (Intradermoréaction)",
    "Test IGRA (Quantiferon)",
    "Recherche de BK dans les crachats",
    "Culture BK",
    "PCR Tuberculose",
    "Test de sensibilité aux antibiotiques",
    "Radiographie thoracique",
  ],
  "Infections bactériennes": [
    "Hémocultures",
    "ECBU",
    "Prélèvement de gorge",
    "Prélèvement nasal",
    "Prélèvement de plaie",
    "Coproculture",
    "Recherche de toxines",
    "Antibiogramme",
  ],
  "Infections parasitaires": [
    "Goutte épaisse",
    "Frottis sanguin",
    "Examen parasitologique des selles",
    "Recherche d'amibes",
    "Recherche de Giardia",
    "Sérologie toxoplasmose",
    "Sérologie paludisme",
  ],
  "Infections fongiques": [
    "Examen mycologique",
    "Culture fongique",
    "Recherche de Candida",
    "Recherche de Cryptococcus",
    "Antifongigramme",
    "Recherche d'aspergillus",
  ],
  "Infections sexuellement transmissibles": [
    "TPHA",
    "VDRL",
    "Recherche de Chlamydia",
    "Recherche de Gonocoque",
    "Sérologie Herpès",
    "Recherche de Mycoplasme",
    "Recherche d'Ureaplasma",
  ],
  "Infections émergentes": [
    "PCR COVID-19",
    "Test antigénique COVID-19",
    "Sérologie COVID-19",
    "PCR Dengue",
    "PCR Chikungunya",
    "PCR Zika",
    "Sérologie Ebola",
    "Sérologie Lassa",
  ],
}

export const SYMPTOMES_MALINF = [
  "Fièvre",
  "Frissons",
  "Sueurs",
  "Fatigue intense",
  "Ganglions enflés",
  "Éruptions cutanées",
  "Toux",
  "Difficulté à respirer",
  "Diarrhée",
  "Vomissements",
  "Maux de tête",
  "Douleurs musculaires",
  "Douleurs articulaires",
  "Perte de poids",
  "Anorexie",
  "Confusion",
  "Raideur de la nuque",
  "Sensibilité à la lumière",
]

export const PATHOLOGIES_MALINF = [
  "VIH/SIDA",
  "Tuberculose",
  "Hépatite A",
  "Hépatite B",
  "Hépatite C",
  "Paludisme",
  "Méningite",
  "Encéphalite",
  "Pneumonie",
  "Gastro-entérite infectieuse",
  "Typhoïde",
  "Dysenterie",
  "Choléra",
  "Dengue",
  "Chikungunya",
  "Zika",
  "Ebola",
  "Lassa",
  "COVID-19",
  "Grippe",
  "Syphilis",
  "Gonorrhée",
  "Chlamydia",
  "Herpès génital",
  "Toxoplasmose",
  "Amibiase",
  "Giardiase",
  "Candidose",
  "Aspergillose",
  "Cryptococcose",
  "Septicémie",
  "Endocardite",
  "Ostéomyélite",
]

export const TRAITEMENTS_MALINF = [
  "Antibiotiques",
  "Antiviraux",
  "Antifongiques",
  "Antiparasitaires",
  "Antirétroviraux",
  "Traitement antituberculeux",
  "Traitement antipaludéen",
  "Immunoglobulines",
  "Vaccins",
  "Prophylaxie post-exposition",
  "Traitement préventif",
  "Isolement",
  "Mesures d'hygiène",
  "Traitement symptomatique",
  "Réhydratation",
  "Support nutritionnel",
]

export const C_MALINF = {
  primary: "#16a34a",
  primarySoft: "#f0fdf4",
  secondary: "#15803d",
  border: "#bbf7d0",
}

export default { EXAMENS_MALINF, SYMPTOMES_MALINF, PATHOLOGIES_MALINF, TRAITEMENTS_MALINF, C_MALINF }