/**
 * ═══════════════════════════════════════════════════════════
 *  NEUROLOGIE — Constantes & Examens spécifiques
 *  ═══════════════════════════════════════════════════════════
 */

// Examens spécifiques à la neurologie
export const EXAMENS_NEURO = {
  "Électrophysiologie": [
    "Électroencéphalogramme (EEG)",
    "EEG de sommeil",
    "EEG vidéo",
    "Électromyogramme (EMG)",
    "Électroneurogramme (ENG)",
    "Potentiels évoqués visuels (PEV)",
    "Potentiels évoqués auditifs (PEA)",
    "Potentiels évoqués somesthésiques (PES)",
    "Potentiels évoqués moteurs (PEM)",
  ],
  "Imagerie neurologique": [
    "IRM cérébrale",
    "IRM médullaire",
    "IRM de diffusion",
    "IRM de perfusion",
    "IRM fonctionnelle",
    "Scanner cérébral",
    "Angio-IRM",
    "Angio-scanner",
    "Artériographie",
    "Myélographie",
  ],
  "Explorations vasculaires": [
    "Échodoppler des troncs supra-aortiques",
    "Échodoppler transcranien",
    "Échodoppler des artères vertébrales",
    "Mesure de la pression artérielle cérébrale",
  ],
  "Examens du liquide céphalo-rachidien": [
    "Ponction lombaire",
    "Analyse du LCR",
    "Recherche de bandes oligoclonales",
    "Dosage des protéines",
    "Dosage de la glycorachie",
    "Recherche de cellules",
    "Recherche microbiologique",
  ],
  "Bilan biologique": [
    "Vitamine B12",
    "Acide folique",
    "Cuivre",
    "Céruléoplasmine",
    "Porphyries",
    "Anticorps anti-récepteurs à l'acétylcholine",
    "Anticorps anti-MuSK",
    "Anticorps anti-can calcique",
    "Anticorps onconeuraux",
    "Marqueurs inflammatoires",
  ],
  "Tests cognitifs et fonctionnels": [
    "Bilan neuropsychologique",
    "Test de Mini-Mental State (MMSE)",
    "Test de l'horloge",
    "Échelle de depression",
    "Échelle d'anxiété",
    "Test de marche",
    "Évaluation de l'équilibre",
  ],
}

// Symptômes spécifiques neurologie
export const SYMPTOMES_NEURO = [
  "Maux de tête (céphalées)",
  "Migraine",
  "Vertiges",
  "Troubles de l'équilibre",
  "Troubles de la marche",
  "Faiblesse musculaire",
  "Paralysie",
  "Engourdissements",
  "Fourmillements",
  "Douleurs neuropathiques",
  "Tremblements",
  "Mouvements anormaux",
  "Troubles de la parole",
  "Troubles de la déglutition",
  "Troubles de la vision",
  "Troubles de la mémoire",
  "Troubles de la concentration",
  "Confusion",
  "Perte de conscience",
  "Crises convulsives",
  "Épilepsie",
  "Troubles du sommeil",
  "Insomnie",
  "Somnolence excessive",
  "Troubles de l'humeur",
  "Anxiété",
  "Dépression",
]

// Pathologies courantes en neurologie
export const PATHOLOGIES_NEURO = [
  "Accident vasculaire cérébral (AVC)",
  "AVC ischémique",
  "AVC hémorragique",
  "Accident ischémique transitoire (AIT)",
  "Épilepsie",
  "Crises épileptiques",
  "Migraine",
  "Céphalée de tension",
  "Algie vasculaire de la face",
  "Névralgie du trijumeau",
  "Maladie de Parkinson",
  "Parkinsonisme",
  "Tremblement essentiel",
  "Maladie d'Alzheimer",
  "Démence",
  "Troubles cognitifs",
  "Sclérose en plaques",
  "Sclérose latérale amyotrophique (SLA)",
  "Maladie de Charcot",
  "Myasthénie",
  "Neuropathie périphérique",
  "Névrite",
  "Radiculalgie",
  "Sciatique",
  "Cruralgie",
  "Syndrome du canal carpien",
  "Méningite",
  "Encéphalite",
  "Tumeur cérébrale",
  "Hydrocéphalie",
  "Hypertension intracrânienne",
  "Traumatisme crânien",
  "Commotion cérébrale",
  "Maladie de Huntington",
  "Dystonie",
  "Tics",
  "Syndrome de Gilles de la Tourette",
]

// Traitements courants en neurologie
export const TRAITEMENTS_NEURO = [
  "Anticonvulsivants",
  "Anti-épileptiques",
  "Antiparkinsoniens",
  "Lévodopa",
  "Agonistes dopaminergiques",
  "Inhibiteurs de l'acétylcholinestérase",
  "Mémantine",
  "Antidépresseurs",
  "Anxiolytiques",
  "Myorelaxants",
  "Corticoïdes",
  "Immunosuppresseurs",
  "Interférons",
  "Anticorps monoclonaux",
  "Anticoagulants",
  "Antiagrégants plaquettaires",
  "Antihypertenseurs",
  "Statines",
  "Vitamines B",
  "Gabapentine",
  "Prégabaline",
  "Triptans",
  "Bêta-bloquants",
  "Toxine botulique",
  "Stimulation cérébrale profonde",
]

// Couleurs spécifiques
export const C_NEURO = {
  primary: "#7c3aed",     // Violet neurologie
  primarySoft: "#f5f3ff",
  secondary: "#6d28d9",
  border: "#ddd6fe",
}

export default {
  EXAMENS_NEURO,
  SYMPTOMES_NEURO,
  PATHOLOGIES_NEURO,
  TRAITEMENTS_NEURO,
  C_NEURO,
}