/**
 * ═══════════════════════════════════════════════════════════
 *  GYNÉCOLOGIE — Constantes & Examens spécifiques
 *  ═══════════════════════════════════════════════════════════
 */

// Examens spécifiques à la gynécologie
export const EXAMENS_GYNECO = {
  "Gynécologie obstétricale": [
    "Échographie obstétricale",
    "Échographie du 1er trimestre",
    "Échographie du 2e trimestre",
    "Échographie du 3e trimestre",
    "Échographie morphologique",
    "Échographie de datation",
    "Échographie avec mesure de la clarté nucale",
    "Doppler ombilical",
    "Monitoring fœtal (RCF)",
    "Test non stressant (NST)",
    "Test de contractions (OCT)",
    "Amniocentèse",
    "Choriovillus sampling (CVS)",
    "Cordocentèse",
  ],
  "Gynécologie générale": [
    "Échographie pelvienne",
    "Échographie endovaginale",
    "Échographie mammaire",
    "Mammographie",
    "Frottis cervico-vaginal",
    "Colposcopie",
    "Biopsie du col",
    "Hystéroscopie diagnostique",
    "Hystéroscopie opératoire",
    "Cœlioscopie",
    "Hystérosalpingographie",
    "Hystérosonographie",
  ],
  "Bilan hormonal": [
    "FSH",
    "LH",
    "Œstradiol",
    "Progestérone",
    "Prolactine",
    "Testostérone",
    "AMH (Hormone Anti-Müllérienne)",
    "Inhibine B",
    "β-HCG",
    "TSH",
    "T3",
    "T4",
    "Cortisol",
  ],
  "Bilan infectieux": [
    "Prélèvement vaginal",
    "Prélèvement cervical",
    "Prélèvement urétral",
    "Recherche de Chlamydia",
    "Recherche de Gonocoque",
    "Recherche de Trichomonas",
    "Recherche de Candida",
    "Recherche de Mycoplasme",
    "Recherche d'Ureaplasma",
    "Sérologie VIH",
    "Sérologie Hépatite B",
    "Sérologie Hépatite C",
    "Sérologie Syphilis (TPHA/VDRL)",
    "Sérologie Rubéole",
    "Sérologie Toxoplasmose",
    "Sérologie CMV",
    "Sérologie Herpès",
  ],
  "Bilan de fertilité": [
    "Bilan d'ovulation",
    "Courbe de température",
    "Test de Hühner",
    "Spermogramme du partenaire",
    "Exploration hormonale complète",
    "Bilan immunologique",
    "Caryotype",
  ],
  "Marqueurs tumoraux": [
    "CA 125",
    "CA 15-3",
    "ACE",
    "AFP",
    "β-HCG",
    "Inhibine",
  ],
}

// Symptômes spécifiques gynécologie
export const SYMPTOMES_GYNECO = [
  "Saignements anormaux",
  "Métrorragies",
  "Ménorragies",
  "Spanioménorrhée",
  "Aménorrhée",
  "Dysménorrhée",
  "Douleurs pelviennes",
  "Leucorrhées",
  "Prurit vulvaire",
  "Brûlures urinaires",
  "Dyspareunie",
  "Mastodynie",
  "Nodule mammaire",
  "Écoulement mamelonnaire",
  "Bouffées de chaleur",
  "Troubles du cycle",
  "Infertilité",
  "Nausées de la grossesse",
  "Vomissements",
  "Contractions utérines",
  "Perte de liquide amniotique",
  "Diminution des mouvements fœtaux",
]

// Pathologies courantes en gynécologie
export const PATHOLOGIES_GYNECO = [
  "Grossesse normale",
  "Grossesse à risque",
  "Menace d'accouchement prématuré",
  "Pré-éclampsie",
  "Diabète gestationnel",
  "Chorioamniotite",
  "Hémorragie du 1er trimestre",
  "Fausses couches",
  "Grossesse extra-utérine",
  "Môle hydatiforme",
  "Fibrome utérin",
  "Endométriose",
  "Adénomyose",
  "Kyste ovarien",
  "Syndrome des ovaires polykystiques",
  "Infections génitales basses",
  "Salpingite",
  "Pelvipéritonite",
  "Prolapsus génital",
  "Incontinence urinaire",
  "Cancer du col",
  "Cancer de l'endomètre",
  "Cancer de l'ovaire",
  "Cancer du sein",
  "Mastopathie",
  "Ostéoporose post-ménopausique",
]

// Traitements courants en gynécologie
export const TRAITEMENTS_GYNECO = [
  "Progestatifs",
  "Œstro-progestatifs",
  "Pilule contraceptive",
  "DIU au cuivre",
  "DIU hormonal",
  "Implant contraceptif",
  "Patch contraceptif",
  "Anneau vaginal",
  "Pilule du lendemain",
  "Acide folique",
  "Fer",
  "Calcium + Vitamine D",
  "Antibiotiques",
  "Antifongiques",
  "Antispasmodiques",
  "AINS",
  "Tocolytiques",
  "Corticoïdes",
  "Insuline",
  "Ocytocique",
  "Prostaglandines",
]

// Couleurs spécifiques
export const C_GYNECO = {
  primary: "#d946ef",     // Violet gynécologie
  primarySoft: "#faf5ff",
  secondary: "#a855f7",
  border: "#f0abfc",
}

export default {
  EXAMENS_GYNECO,
  SYMPTOMES_GYNECO,
  PATHOLOGIES_GYNECO,
  TRAITEMENTS_GYNECO,
  C_GYNECO,
}