/**
 * ═══════════════════════════════════════════════════════════
 *  STOMATOLOGIE — Constantes & Examens spécifiques
 *  ═══════════════════════════════════════════════════════════
 */

export const EXAMENS_STOMATO = {
  "Examens cliniques": [
    "Examen endobuccal complet",
    "Examen parodontal",
    "Examen occlusal",
    "Examen des muqueuses",
    "Examen des gencives",
    "Test de vitalité pulpaire",
    "Examen des articulations temporo-mandibulaires",
    "Palpation des ganglions",
  ],
  "Imagerie dentaire": [
    "Radiographie rétro-alvéolaire",
    "Radiographie panoramique",
    "Cliché rétro-alvéolaire",
    "Cliché péri-apical",
    "Scanner dentaire (Cone Beam)",
    "Téléradiographie",
    "Céphalométrie",
    "Sialographie",
  ],
  "Examens de laboratoire": [
    "Prélèvement bactériologique",
    "Antibiogramme",
    "Biopsie buccale",
    "Anatomopathologie",
    "Recherche de Candida",
    "Recherche d'Herpès",
    "Cytologie exfoliative",
  ],
  "Examens fonctionnels": [
    "Enregistrement occlusal",
    "Analyse de la marche occlusale",
    "Test de mobilité dentaire",
    "Mesure de la profondeur sulculaire",
    "Test de sensibilité",
    "Étude de la mastication",
  ],
  "Examens spécialisés": [
    "Parodontogramme",
    "Charting dentaire",
    "Analyse de la salive",
    "pH salivaire",
    "Test de fluxo salivaire",
    "Analyse de la plaque dentaire",
  ],
}

export const SYMPTOMES_STOMATO = [
  "Douleur dentaire",
  "Sensibilité dentinaire",
  "Saignement des gencives",
  "Gonflement des gencives",
  "Mauvaise haleine",
  "Goût désagréable",
  "Mobilité dentaire",
  "Aphtes",
  "Ulcérations buccales",
  "Lésions blanches",
  "Lésions rouges",
  "Gonflement de la face",
  "Difficulté à ouvrir la bouche",
  "Douleur de la mâchoire",
  "Craquements articulaires",
  "Sécheresse buccale",
  "Salivation excessive",
  "Difficulté à avaler",
  "Difficulté à parler",
  "Perte de goût",
]

export const PATHOLOGIES_STOMATO = [
  "Caries dentaires",
  "Pulpite",
  "Nécrose pulpaire",
  "Abcès dentaire",
  "Parodontite",
  "Gingivite",
  "Déchaussement dentaire",
  "Maladie parodontale",
  "Aphtose",
  "Stomatite",
  "Glossite",
  "Candidose buccale",
  "Herpès buccal",
  "Leucoplasie",
  "Lichen plan buccal",
  "Cancer de la bouche",
  "Cancer de la langue",
  "Kyste odontogène",
  "Dent de sagesse incluse",
  "Malocclusion",
  "Bruxisme",
  "Dysfonction temporo-mandibulaire",
  "Névralgie du trijumeau",
  "Fente labiale",
  "Fente palatine",
  "Anomalies du développement",
  "Traumatisme dentaire",
  "Fracture dentaire",
  "Luxation dentaire",
  "Avulsion dentaire",
]

export const TRAITEMENTS_STOMATO = [
  "Détartrage",
  "Surfaçage",
  "Polissage",
  "Obturation (plombage)",
  "Inlay/Onlay",
  "Couronne",
  "Bridge",
  "Prothèse amovible",
  "Implant dentaire",
  "Dévitalisation",
  "Traitement de canal",
  "Apicectomie",
  "Extraction dentaire",
  "Extraction de dent de sagesse",
  "Greffes gingivales",
  "Chirurgie parodontale",
  "Allongement de couronne",
  "Freinectomie",
  "Kystectomie",
  "Biopsie",
  "Antibiotiques",
  "Antifongiques",
  "Antiviraux",
  "Antalgiques",
  "Anti-inflammatoires",
  "Bains de bouche",
  "Orthodontie",
  "Gouttière occlusale",
  "Blanchiment dentaire",
  "Facettes",
]

export const C_STOMATO = {
  primary: "#0284c7",
  primarySoft: "#f0f9ff",
  secondary: "#0369a1",
  border: "#bae6fd",
}

export default { EXAMENS_STOMATO, SYMPTOMES_STOMATO, PATHOLOGIES_STOMATO, TRAITEMENTS_STOMATO, C_STOMATO }